site_name: FFram Documentation
site_url: https://rebuild-it-labs.github.io/FFram/reference
docs_dir: website_docs
site_dir: docs/reference
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Reference:
    - Installation: reference/installation.md
    - Quick Start: reference/quick-start.md
    - Benchmarks: reference/benchmarks.md
markdown_extensions:
  - toc:
      permalink: true
plugins:
  - search
